program: train.py 
name: hyperparam-sweep
project: ConvLSTM
method: random
metric:
  name: test_loss
  goal: minimize
parameters: 
  batch-size: 
    distribution: int_uniform
    min: 32 
    max: 256 
  lr: 
    min: 0.000001
    max: 0.1
  layers: 
    distribution: int_uniform 
    min: 1
    max: 7 
  kernels: 
    distribution: int_uniform
    min: 1 
    max: 100
  activation: 
    values: ["relu", "tanh"]
  optimizer:
    values: ["Adadelta", "Adafactor", "Adagrad", "Adam", "AdamW", "SparseAdam", "Adamax", "ASGD", "LBFGS", "NAdam", "RAdam", "RMSprop", "Rprop", "SGD"]
command: 
  - ${env}
  - "/Users/henrywilliams/Documents/uni/amml/assessment/.venv/bin/python"
  - ${program}
  - ${args}
  
  
