program: train.py 
name: hyperparam-sweep
project: ConvLSTM
method: random
metric:
  name: test_loss
  goal: minimize
parameters: 
  batch-size: 
    distribution: int_uniform
    min: 32 
    max: 256 
  lr: 
    min: 1e-1
    max: 1e-5
  layers: 
    distribution: int_uniform 
    min: 1
    max: 10 
  kernels: 
    distribution: int_uniform
    min: 1 
    max: 100
  activation: 
    distribution: categorical
    values: ["relu", "tanh"]
  optimizer:
    values: ["Adadelta", "Adafactor", "Adagrad", "Adam", "AdamW", "SparseAdam", "Adamax", "ASGD", "LBFGS", "NAdam", "RAdam", "RMSprop", "Rprop", "SGD"]
  weight: 
    min: 0.0
    max: 1.0
  threshold: 
    min: 0.0
    max: 0.0
command: 
  - ${env}
  - "/Users/henrywilliams/Documents/uni/amml/assessment/.venv/bin/python"
  - ${program}
  - ${args}
  
  
